name: CI Pipeline

# Trigger workflow on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs
jobs:
  test:
    runs-on: ubuntu-latest

#    # Specify the testing steps
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      - name: Set Up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.8'  # Use the preferred Python version
#
#      - name: Install Dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt  # Ensure a requirements.txt is present
#          pip install pytest
#
#      - name: Run Tests with pytest
#        run: |
#          pytest tests/ --disable-warnings
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Use the preferred Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure a requirements.txt is present
          pip install pytest

      # Run flake8 for code linting
      - name: Run flake8 Linting
        run: |
          flake8 .
